### ISSUE TITLE
Unable to add Entity type URL or Domain

### ISSUE THREAD

**Issue by bluewhale9981** [paterva/maltego-trx#7]
Hi,

I wanted to report a case that I try to add new URL entity while transforming an URL entity. But that didn't work. I thought may be the XML meta is not correct.

I am using Maltego version: 4.2.10

**Comment by steve-bate** [comment]
I had the same issue. I'm new to Maltego and writing transforms, but I didn't find any information about this in the documentation. By trial and error and studying the XML graph exports I was able to make it work by doing something like the following:
```python
from maltego_trx.entities import URL
# . . . other code
    @classmethod
    def create_entities(cls, message, transform):
        searchUrl = 'www.google.com'
        urlEntity = transform.addEntity(URL)
        urlEntity.addProperty('title', 'Title', 'loose', 'Search Action')
        urlEntity.addProperty('short-title', 'Short Title', 'loose', 'Search Action')
        urlEntity.addProperty('url', 'URL', 'loose', searchUrl)

**Comment by hlawatjt** [comment]
Hi,

Entity Properties are available in the "Entity Manager" in the Maltego Desktop Client and should be used as reference.

**Steps:**

1. Start Maltego Desktop Client.
1. Click on "Entities" in the Menu bar.
![image](https://user-images.githubusercontent.com/43576722/88062711-7ac5a800-cb69-11ea-88f2-c6b7f1dd633e.png)
1. Click on the "Manage Entities" button to open the "Entity Manager".
![image](https://user-images.githubusercontent.com/43576722/88062606-59fd5280-cb69-11ea-9bc7-4904bf2842c9.png)
1. Scroll or use the search bar to find the Entity you would like to know more about, e.g. "url".
1. Click on the 3 dots "..." to view die Entity Details.
![image](https://user-images.githubusercontent.com/43576722/88062804-95981c80-cb69-11ea-9493-8c4fb19901ef.png)
1. Select the "Additional Properties" tab for property information.
![image](https://user-images.githubusercontent.com/43576722/88062906-b3658180-cb69-11ea-9872-8638a3c3b1a2.png)
1. Select any property to to see detail information about the property.
![image](https://user-images.githubusercontent.com/43576722/88063137-fde6fe00-cb69-11ea-9d84-f44fb934de11.png)
1. Now use the "addProperty" function to add and set property values in your transform:

**Notes:**

You can add custom Properties to standard Entities. However, where possible, try to use the standard Entities as they are as to ensure that your transforms return Entities that can be used by other transforms as well.

**Comment by steve-bate** [comment]
Thanks. This is great information. However, it doesn't really address the original issue. When I look at the UI information, none of the properties are flagged as required and yet they appear to be so in a custom transform context (at least some of them are, I didn't try various permutations to see if they work).

**Comment by hlawatjt** [comment]
You'll notice that at least one property can't be deleted. At minimum you would need to set that property.

In the URL Entity example, the property with Name = "url" would need to be set.

If we look at the AS Entity, it has only one property with Name = "as.number", which would need to be set.

**Comment by steve-bate** [comment]
Thanks again. As a noob transform developer, I think a confusing aspect of maltego-trx is that `addEntity` takes an entity type and a `value`. One would assume the `value` is the URL in this case. However, it apparently is not. I'm guessing `value` is ignored unless there's only one property (maybe?). It might be useful to use it if there's only one _required_ property (and maybe throw an exception in other cases instead of ignoring it). Thoughts?

**Comment by phdowling** [comment]
Hi @steve-bate  - there are a few entities in Maltego (and I believe URL and Image are among them) that work a bit inconsistently due to legacy Maltego versions. There can be two aspects to this as far as I've seen:
1) Just setting the value is (sometimes) not enough. I believe this is the case for maltego.Image entities, there you need to set both the description(value or property) and url (property)
2) property names are in rare cases misleading, i.e. your server has to set a different property than what the client says the property is called. 

For maltego.URL, the "value" only sets the "short-title" property. **Here, if only the value is set, the Maltego client will refuse to even return the entity to the graph** (I do not know technically why this is the case, but it is). To set the url itself properly and to therefore return the entity to the graph, **you must set the "theurl" property** (not "url", as the entity manager states incorrectly).

For Image, the "value" actually sets only the description. Further, **the image URL property is actually called "fullImage" and the description property is called "properties.image"** (while the Maltego client incorrectly states them as "description" and "url" in the entity manager). Unlike URLs, an incomplete Image entity does get returned to the graph, it will just not be useful to other Transforms. To correctly return an image, you may use the constructor to set the description, and then add the "fullImage" property to set the URL.
